# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  terraform: circleci/terraform@3.2.0
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# run this
jobs:
  ermetic-scan:
    docker:
      - image: ghcr.io/ermetic/scanner:latest
        environment:
          ERMETIC_PIPELINE_RUN_TRIGGER: push
    steps:
      - run:
          name: 'Install Git'
          command: apk add --update openssh-client git
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run:
          name: 'Ermetic Scanner'
          command: |
            export ERMETIC_CODE_BRANCH=${CIRCLE_BRANCH} >> "$BASH_ENV"
            export ERMETIC_CODE_COMMIT_HASH=${CIRCLE_SHA1} >> "$BASH_ENV"
            export ERMETIC_CODE_COMMIT_USER=${CIRCLE_USERNAME} >> "$BASH_ENV"
            export ERMETIC_PIPELINE_RUN_ID=${CIRCLE_BUILD_NUM} >> "$BASH_ENV"
            export ERMETIC_PIPELINE_RUN_URL=${CIRCLE_BUILD_URL} >> "$BASH_ENV"
            export ERMETIC_CODE_REPOSITORY_URL=${CIRCLE_REPOSITORY_URL} >> "$BASH_ENV"
            echo $ERMETIC_PIPELINE_RUN_ID
            source "$BASH_ENV"
            ermetic iac scan

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  scan-terraform-workflow:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
      - terraform/validate:
          checkout: true
          context: terraform
          requires:
            - terraform/fmt
      # - terraform/plan:
      #     checkout: true
      #     context: terraform
      #     persist-workspace: true
      #     requires:
      #       - terraform/validate
      - ermetic-scan:
          requires:
            - terraform/validate
